repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt"]
        exclude_types: ["jupyter"]

  # To be activated after quick dev cycles
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #   - id: pydocstyle
  #     additional_dependencies: [toml]
  #     exclude: "tests/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml

  # this validates our github workflow files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-vv, -m, -p, -S, -s, -n, --fail-under=100]
        files: src

  # - repo: https://github.com/ansys/pre-commit-hooks
  #   rev: v0.2.9
  #   hooks:
  #     - id: add-license-headers
  #       args:
  #         - --start_year=2023

  - repo: local
    hooks:
      - id: uncomment-coverage-options
        name: uncomment-coverage-options
        language: python
        entry: python dev/scripts/uncomment_code_coverage.py
