repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args:
    - --fix
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args:
    - --ignore-words
    - doc/styles/config/vocabularies/ANSYS/accept.txt
    exclude_types:
    - jupyter

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.24.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
  - id: interrogate
    args:
    - -vv
    - -m
    - -p
    - -S
    - -s
    - -n
    - --fail-under=100
    files: src

- repo: local
  hooks:
  - id: uncomment-coverage-options
    name: uncomment-coverage-options
    language: python
    entry: python dev/scripts/uncomment_code_coverage.py

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2022
